In [14]:
# Import necessary libraries
import numpy as np
from sklearn.linear_model import LogisticRegression
from tensorflow.keras.datasets import cifar10
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
# Load CIFAR-10 dataset from Keras
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

In [15]:
# Reshape the data
X_train = X_train.reshape(X_train.shape[0], -1)
X_test = X_test.reshape(X_test.shape[0], -1)

# Normalize the data
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') / 255

In [16]:
# Flatten the labels
y_train = y_train.flatten()
y_test = y_test.flatten()

In [17]:
# Initialize the Logistic Regression model
model = LogisticRegression()

In [18]:
# Train the model
model.fit(X_train, y_train)

# Make predictions
predictions = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, predictions)

print("Accuracy of Logistic Regression on CIFAR-10: {:.2f}%".format(accuracy * 100))
print("Accuracy of Logistic Regression on CIFAR-10: {:.2f}%".format(accuracy * 100))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy of Logistic Regression on CIFAR-10: 40.51%
Accuracy of Logistic Regression on CIFAR-10: 40.51%


In [19]:
# Print classification report
print("Classification Report:")
print(classification_report(y_test, predictions))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions))

Classification Report:
              precision    recall  f1-score   support

           0       0.43      0.48      0.45      1000
           1       0.47      0.49      0.48      1000
           2       0.32      0.28      0.30      1000
           3       0.31      0.23      0.27      1000
           4       0.36      0.29      0.32      1000
           5       0.33      0.37      0.35      1000
           6       0.42      0.49      0.45      1000
           7       0.46      0.44      0.45      1000
           8       0.47      0.52      0.49      1000
           9       0.43      0.46      0.44      1000

    accuracy                           0.41     10000
   macro avg       0.40      0.41      0.40     10000
weighted avg       0.40      0.41      0.40     10000

Confusion Matrix:
[[479  42  59  30  19  38  26  53 184  70]
 [ 60 494  21  28  22  41  37  53  78 166]
 [112  47 276  80 115  93 138  67  48  24]
 [ 42  60  96 235  56 218 127  48  45  73]
 [ 57  28 135  47 291 106 15

## Applying CV on Colored Image


In [21]:
from sklearn.model_selection import cross_val_score
for k in [3, 5, 10]:
    scores = cross_val_score(model, X_train_gray, y_train, cv=k)
    avg_accuracy = np.mean(scores)
    print(f"Average Accuracy for k={k} cross-validation: {avg_accuracy * 100:.2f}%")

Average Accuracy for k=3 cross-validation: 15.52%
Average Accuracy for k=5 cross-validation: 22.56%
Average Accuracy for k=10 cross-validation: 22.56%


## Applying on grayscale

In [ ]:
# Import necessary libraries
import numpy as np
from sklearn.linear_model import LogisticRegression
from tensorflow.keras.datasets import cifar10
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from skimage.color import rgb2gray

# Load CIFAR-10 dataset from Keras
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

# Convert RGB images to grayscale
X_train_gray = rgb2gray(X_train)
X_test_gray = rgb2gray(X_test)

# Reshape the data
X_train_gray = X_train_gray.reshape(X_train_gray.shape[0], -1)
X_test_gray = X_test_gray.reshape(X_test_gray.shape[0], -1)

# Normalize the data
X_train_gray = X_train_gray.astype('float32') / 255
X_test_gray = X_test_gray.astype('float32') / 255

# Flatten the labels
y_train = y_train.flatten()
y_test = y_test.flatten()

In [ ]:
# Reshape the data
X_train_gray = X_train_gray.reshape(X_train_gray.shape[0], -1)
X_test_gray = X_test_gray.reshape(X_test_gray.shape[0], -1)

# Normalize the data
X_train_gray = X_train_gray.astype('float32') / 255
X_test_gray = X_test_gray.astype('float32') / 255

# Flatten the labels
y_train = y_train.flatten()
y_test = y_test.flatten()

In [ ]:
# Initialize the Logistic Regression model
model = LogisticRegression(max_iter=1000)

# Train the model
model.fit(X_train_gray, y_train)

# Make predictions
predictions = model.predict(X_test_gray)

# Calculate accuracy
accuracy = accuracy_score(y_test, predictions)

print("Accuracy of Logistic Regression on Grayscale CIFAR-10: {:.2f}%".format(accuracy * 100))

In [ ]:
# Print classification report
print("Classification Report:")
print(classification_report(y_test, predictions))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions))


## Applying CV on Grayscale

In [ ]:
from sklearn.model_selection import cross_val_score
for k in [3, 5, 10]:
    scores = cross_val_score(model, X_train_gray, y_train, cv=k)
    avg_accuracy = np.mean(scores)
    print(f"Average Accuracy for k={k} cross-validation: {avg_accuracy * 100:.2f}%")